baseURL = "https://nightsky.fun"
languageCode = "zh-cn"
title = "业余天文志"
copyright = "Copyright (c) 2017-2021. All rights reserved."
theme = "liquorice"
builddrafts = false
hasCJKLanguage = true
googleAnalytics = "UA-115183027-2"

[outputFormats.RSS]
baseName = "feed"

[permalinks]
    post = "/post/:filename"

[[menu.main]]
    name = "存档"
    pre = "<i class='fa fa-heart'></i>"
    weight = 1
    url = "/post/"
[[menu.main]]
    name = "关于"
    pre = "<i class='fa fa-road'></i>"
    weight = 2
    url = "/about/"

[params]
    author = "Venj"
    DateForm = "2006年01月02日"
    copyright = "版权所有 © 2017-2021 Venj Chu 业余天文志"
